application: cockyreaders-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css/
 
- url: /js
  static_dir: js/
 
- url: /library
  static_dir: library/
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: latest